spring:
  redis:
    host: 192.168.1.85
    port: 6379
    #一定要手动配置lettuce的连接池,不然连接池不会生效
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-idle: 8 #最大活跃连接
        min-idle: 0 #最小活跃连接
        max-wait: 1000 #连接最大等待时间
    database: 0
